// Generated by https://quicktype.io

export interface Article {
    article_id:    string;
    category:      string;
    code:          string;
    name:          string;
    image_url:     string;
    selling_price: string;
    stock:         number;
    description:   string;
    status:        number;
    created_at:    string;
}
